### ISSUE TITLE
想问一下，为什么安装了matplotlib3.9.2还是一直报错呀

### ISSUE THREAD

**Issue by hhhhh-dei** [AuroraEchos/Automatic-modulation-recognition#2]
Traceback (most recent call last):
  File "D:\AAAdybrqs\Automatic-modulation-recognition-main\train.py", line 16, in <module>
    from data_processor import RMLDataProcessor
  File "D:\AAAdybrqs\Automatic-modulation-recognition-main\data_processor.py", line 8, in <module>
    import matplotlib.pyplot as plt
  File "D:\Anaconda\envs\DL\lib\site-packages\matplotlib\__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "D:\Anaconda\envs\DL\lib\site-packages\matplotlib\cbook\__init__.py", line 32, in <module>
    from matplotlib._api.deprecation import (
ImportError: cannot import name 'mplDeprecation' from 'matplotlib._api.deprecation' (D:\Anaconda\envs\DL\lib\site-packages\matplotlib\_api\deprecation.py)

**Comment by AuroraEchos** [comment]
你好，这个问题可能是由于 matplotlib 版本和当前环境存在兼容性问题。这是一个绘图工具，一般而言这个库是不会出现问题的，我的建议是卸载并重新安装，并且不要指定特定的版本号，这样会自动安装合适的版本，你可以通过下面的命令进行操作:
pip uninstall matplotlib
pip install matplotlib
